<div class="p-6 md:p-8">
    <div class="mb-6"><h1 class="text-2xl font-bold text-slate-900">Media Library</h1><p class="mt-1 text-sm text-slate-500">Simpan aset gambar, PDF, dan video di satu tempat agar dapat digunakan ulang oleh halaman dan Homepage Builder.</p></div>
    @if(session('media-message'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('media-message') }}</div>@endif
    <form wire:submit="upload" class="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="grid gap-4 md:grid-cols-4"><div class="md:col-span-2"><label class="mb-1 block text-sm font-semibold">File</label><input type="file" wire:model="file" class="w-full text-sm">@error('file')<p class="text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><label class="mb-1 block text-sm font-semibold">Kategori</label><select wire:model="category" class="w-full rounded-xl border border-slate-300 px-3 py-2.5"><option value="general">Umum</option><option value="image">Gambar</option><option value="document">Dokumen</option><option value="video">Video</option><option value="branding">Branding</option></select></div><div><label class="mb-1 block text-sm font-semibold">Alt Text</label><input wire:model="alt_text" class="w-full rounded-xl border border-slate-300 px-3 py-2.5"></div></div><button class="mt-4 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white">Upload Media</button></form>
    <div class="mb-4"><input wire:model.live.debounce.300ms="search" placeholder="Cari file..." class="w-full max-w-md rounded-xl border border-slate-300 px-3 py-2.5"></div>
    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        @foreach($assets as $asset)<article class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex h-40 items-center justify-center bg-slate-100">@if(str_starts_with($asset->mime_type ?? '', 'image/'))<img src="{{ $asset->url }}" alt="{{ $asset->alt_text ?: $asset->name }}" class="h-full w-full object-cover">@else<div class="text-center text-slate-500"><div class="text-3xl">📄</div><div class="mt-2 text-xs">{{ $asset->mime_type }}</div></div>@endif</div><div class="p-4"><div class="truncate text-sm font-bold">{{ $asset->name }}</div><div class="mt-1 text-xs text-slate-500">{{ number_format($asset->size/1024,1) }} KB · {{ $asset->category }}</div><input readonly value="{{ $asset->url }}" onclick="this.select()" class="mt-3 w-full rounded-lg border border-slate-200 bg-slate-50 px-2 py-1.5 text-[11px]"><div class="mt-3 flex justify-between"><a href="{{ $asset->url }}" target="_blank" class="text-xs font-semibold text-blue-600">Buka</a><button wire:click="delete({{ $asset->id }})" wire:confirm="Hapus media ini?" class="text-xs font-semibold text-rose-600">Hapus</button></div></div></article>@endforeach
    </div><div class="mt-5">{{ $assets->links() }}</div>
</div>
