<div class="p-6 md:p-8">
    <div class="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-2xl font-bold text-slate-900">Manajemen Halaman</h1><p class="mt-1 text-sm text-slate-500">Custom Page mendukung Draft/Publish, SEO, banner, dan Media Library.</p></div><button wire:click="openCreate" class="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">+ Tambah Halaman</button></div>
    @if(session('page-message'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('page-message') }}</div>@endif
    @if($showForm)
    <form wire:submit="save" class="mb-7 space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <div class="grid gap-5 md:grid-cols-2"><div><label class="mb-1 block text-sm font-semibold">Judul</label><input wire:model.live.debounce.400ms="title" class="w-full rounded-xl border border-slate-300 px-3 py-2.5"></div><div><label class="mb-1 block text-sm font-semibold">Slug URL</label><input wire:model="slug" class="w-full rounded-xl border border-slate-300 px-3 py-2.5"></div><div class="md:col-span-2"><label class="mb-1 block text-sm font-semibold">Ringkasan</label><textarea wire:model="excerpt" rows="2" class="w-full rounded-xl border border-slate-300 px-3 py-2.5"></textarea></div><div class="md:col-span-2"><label class="mb-1 block text-sm font-semibold">Konten</label><textarea wire:model="content" rows="12" class="w-full rounded-xl border border-slate-300 px-3 py-2.5"></textarea></div></div>
        <div class="grid gap-5 md:grid-cols-2"><div class="rounded-xl border border-slate-200 p-4"><label class="text-sm font-bold">Banner</label><input type="file" wire:model="banner" accept="image/*" class="mt-2 block w-full text-sm"><select wire:model="banner_media_id" class="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">atau pilih Media Library</option>@foreach($mediaImages as $media)<option value="{{ $media->id }}">{{ $media->name }}</option>@endforeach</select>@if($existingBanner)<p class="mt-1 truncate text-xs text-slate-500">Saat ini: {{ $existingBanner }}</p>@endif</div><div><label class="mb-1 block text-sm font-semibold">Jadwal Publikasi</label><input type="datetime-local" wire:model="published_at" class="w-full rounded-xl border border-slate-300 px-3 py-2.5"><label class="mt-4 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" wire:model="is_published"> Publish halaman</label></div></div>
        <section class="rounded-xl border border-blue-100 bg-blue-50/40 p-5"><h3 class="font-bold text-slate-900">SEO Halaman</h3><div class="mt-4 grid gap-4 md:grid-cols-2"><div><label class="mb-1 block text-sm font-semibold">SEO Title</label><input wire:model="seo_title" class="w-full rounded-xl border border-slate-300 px-3 py-2.5" placeholder="Kosong = gunakan judul halaman"></div><div class="md:col-span-2"><label class="mb-1 block text-sm font-semibold">Meta Description</label><textarea wire:model="seo_description" rows="2" class="w-full rounded-xl border border-slate-300 px-3 py-2.5"></textarea></div><div><label class="mb-1 block text-sm font-semibold">OG Image</label><input type="file" wire:model="seo_og" accept="image/*" class="block w-full text-sm"><select wire:model="seo_og_media_id" class="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">atau Media Library</option>@foreach($mediaImages as $media)<option value="{{ $media->id }}">{{ $media->name }}</option>@endforeach</select></div><label class="mt-7 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" wire:model="robots_index"> Izinkan indexing</label></div></section>
        <div class="flex gap-3"><button class="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white">Simpan</button><button type="button" wire:click="cancel" class="rounded-xl border border-slate-300 px-5 py-2.5 text-sm font-semibold">Batal</button></div>
    </form>@endif
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Halaman</th><th class="px-5 py-3">URL</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($pages as $page)<tr><td class="px-5 py-4"><div class="font-semibold">{{ $page->title }}</div><div class="mt-1 max-w-lg truncate text-xs text-slate-500">{{ $page->excerpt }}</div></td><td class="px-5 py-4"><code>/page/{{ $page->slug }}</code></td><td class="px-5 py-4"><button wire:click="togglePublish({{ $page->id }})" class="rounded-full px-2 py-1 text-xs font-semibold {{ $page->is_published?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700' }}">{{ $page->is_published?'Published':'Draft' }}</button></td><td class="px-5 py-4"><div class="flex justify-end gap-3">@if($page->is_published)<a href="{{ rtrim(config('app.frontend_url', env('FRONTEND_URL','http://localhost:5174')), '/') }}/page/{{ $page->slug }}" target="_blank" class="font-semibold text-emerald-600">Lihat</a>@endif<button wire:click="edit({{ $page->id }})" class="font-semibold text-blue-600">Edit</button><button wire:click="delete({{ $page->id }})" wire:confirm="Hapus halaman ini?" class="font-semibold text-rose-600">Hapus</button></div></td></tr>@empty<tr><td colspan="4" class="px-5 py-10 text-center text-slate-500">Belum ada custom page.</td></tr>@endforelse</tbody></table></div></div>
</div>
