<div class="p-6 md:p-8" x-data x-on:open-preview.window="window.open($event.detail.url, '_blank')">
    <div class="mb-6"><h1 class="text-2xl font-bold text-slate-900">Preview, Publish & Revision</h1><p class="mt-1 text-sm text-slate-500">Perubahan builder tersimpan sebagai draft. Preview menggunakan token 30 menit; Publish membuat snapshot yang menjadi konfigurasi publik.</p></div>
    @if(session('publish-message'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('publish-message') }}</div>@endif
    <div class="grid gap-6 xl:grid-cols-2">
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Draft → Publik</h2><p class="mt-2 text-sm text-slate-500">Preview menampilkan navbar, homepage, modul, identitas, SEO dan tema draft.</p><div class="mt-5 flex flex-wrap gap-3"><button wire:click="generatePreview" class="rounded-xl border border-blue-300 bg-blue-50 px-4 py-2.5 text-sm font-semibold text-blue-700">Preview Website</button></div>@if($previewUrl)<input readonly onclick="this.select()" value="{{ $previewUrl }}" class="mt-3 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs">@endif<div class="mt-6"><label class="mb-1 block text-sm font-semibold">Catatan Publikasi</label><input wire:model="label" class="w-full rounded-xl border border-slate-300 px-3 py-2.5" placeholder="Contoh: Update navbar HUT RI"><button wire:click="publish" wire:confirm="Publish seluruh konfigurasi draft ke website publik?" class="mt-3 rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-semibold text-white">Publish Website</button></div></section>
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Export / Import Konfigurasi</h2><p class="mt-2 text-sm text-slate-500">Memindahkan theme, identitas teks, modul, navbar, dan homepage. File media fisik tidak ikut disalin.</p><button wire:click="exportConfig" class="mt-5 rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold">Export JSON</button><div class="mt-5 border-t pt-5"><input type="file" wire:model="importFile" accept=".json,application/json" class="block w-full text-sm">@error('importFile')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror<button wire:click="importConfig" wire:confirm="Import akan mengganti struktur draft navbar/homepage. Lanjut?" class="mt-3 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Import ke Draft</button></div></section>
    </div>
    <section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b p-5"><h2 class="text-lg font-bold">Revision History</h2><p class="text-sm text-slate-500">Setiap Publish adalah snapshot yang dapat dipulihkan.</p></div><div class="divide-y">@forelse($publications as $pub)<div class="flex flex-wrap items-center justify-between gap-4 p-5"><div><div class="font-bold">v{{ $pub->version }} · {{ $pub->label }}</div><div class="mt-1 text-xs text-slate-500">{{ $pub->created_at->format('d/m/Y H:i') }} · {{ $pub->publisher->name ?? 'System' }}</div></div><button wire:click="restore({{ $pub->id }})" wire:confirm="Pulihkan snapshot ini sebagai versi publik baru?" class="rounded-lg border border-amber-300 bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-700">Pulihkan</button></div>@empty<div class="p-8 text-center text-sm text-slate-500">Belum ada publikasi V3. Klik Publish Website untuk membuat snapshot pertama.</div>@endforelse</div></section>
</div>
